/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-21 12:29:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class entryForNormal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/entryForm.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   function nicknameCheck() {\r\n");
      out.write("      if (document.form.nickname.value == \"\") {\r\n");
      out.write("         alert(\"닉네임을 입력하세요.\");\r\n");
      out.write("         form.nickname.focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      var url = \"../idcheck/nicknamecheck.html?nickname=\"\r\n");
      out.write("            + document.form.nickname.value;\r\n");
      out.write("      window.open(url, \"_blank\", \"width=450,height=200\");\r\n");
      out.write("   }\r\n");
      out.write("   function idCheck() {\r\n");
      out.write("      if (document.form.user_id.value == \"\") {\r\n");
      out.write("         alert(\"ID를 입력하세요.\");\r\n");
      out.write("         frm.id.focus();\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      var url = \"../idcheck/idcheck.html?ID=\"\r\n");
      out.write("            + document.form.user_id.value;\r\n");
      out.write("      window.open(url, \"_blank\", \"width=450,height=200\");\r\n");
      out.write("   }\r\n");
      out.write("      function validate(form) {\r\n");
      out.write("         if (form.name.value == \"\") {\r\n");
      out.write("            form.name.focus();\r\n");
      out.write("            alert(\"이름을 입력해주세요\");\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.id.value == \"\") {\r\n");
      out.write("            alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("            form.id.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.password.value == \"\") {\r\n");
      out.write("            alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("            form.password.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.password.value != form.passwordCheck.value) {\r\n");
      out.write("            alert(\"암호가 일치하지 않습니다.\");\r\n");
      out.write("            form.password.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.nickname.value == \"\") {\r\n");
      out.write("            alert(\"닉네임을 입력해주세요.\");\r\n");
      out.write("            form.nickname.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.email.value == \"\") {\r\n");
      out.write("            alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("            form.email.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.phone1.value == \"\") {\r\n");
      out.write("            alert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("            form.phone1.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.phone2.value == \"\") {\r\n");
      out.write("            alert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("            form.phone2.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.phone3.value == \"\") {\r\n");
      out.write("            alert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("            form.phone3.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.birth.value == \"\") {\r\n");
      out.write("            alert(\"생일을 선택해주세요.\");\r\n");
      out.write("            form.birth.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("         if (form.image.value == \"\") {\r\n");
      out.write("            alert(\"프로필 이미지를 선택해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("   <div class=\"store_container\">\r\n");
      out.write("      <form action=\"../entry/entry.html\" class=\"form\" id=\"fileupload\" name=\"form\"\r\n");
      out.write("         enctype=\"multipart/form-data\" method=\"post\" onSubmit=\"return validate(this)\">\r\n");
      out.write("\r\n");
      out.write("         <div class=\"sidebar\">\r\n");
      out.write("             <a class=\"active\" href=\"#home\">일반 회원 가입</a>\r\n");
      out.write("             <a href=\"../entry/managerlUser.html\">기업 회원 가입</a>             \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"content\">         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("            <label for=\"name\">이름 :</label> \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("             <input type=\"text\" name=\"name\" class=\"name\" id=\"name\" placeholder=\"이름을  입력하세요 \">\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"id\">아이디 : </label>\r\n");
      out.write("            </div>      \r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("               <input type=\"text\" id=\"id\"\r\n");
      out.write("               name=\"user_id\" placeholder=\"아이디를 입력해 주세요.\"><input type=\"hidden\" name=\"idChecked\" id=\"idChecked\" /> <input\r\n");
      out.write("                  type=\"button\" value=\"중복검사\" onClick=\"idCheck()\" />\r\n");
      out.write("            </div>\r\n");
      out.write("                     \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"password\">비밀번호 : </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("            <input type=\"password\" name=\"password\" id=\"password\" class=\"password\" placeholder=\"비밀번호를 입력하세요 .\">\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>         \r\n");
      out.write("      \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"passwordCheck\" >비밀번호 확인 : </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("               <input type=\"password\"\r\n");
      out.write("                  name=\"passwordCheck\" id=\"passwordCheck\" class=\"passwordCheck\" placeholder=\"확인 비밀번호를 입력하세요.\">\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"nickname\">닉네임 : </label></div>\r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("               <input type=\"text\" id=\"nickname\" name=\"nickname\" placeholder=\"사용할 닉네임을 입력해주세요 .\">\r\n");
      out.write("               <input type=\"hidden\" name=\"nicknameChecked\" id=\"nicknameChecked\" /> <input\r\n");
      out.write("                  type=\"button\" value=\"중복검사\" onClick=\"nicknameCheck()\" />\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"email\">이메일 : </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("               <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"이메일 주소를 입력하세요.\"> \r\n");
      out.write("            </div>   \r\n");
      out.write("               \r\n");
      out.write("         </div>      \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row tel\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"phone\">전화번호 : </label>\r\n");
      out.write("            </div>   \r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("            <select path=\"phone1\" name=\"phone1\">\r\n");
      out.write("               <option value=\"02\">02</option>\r\n");
      out.write("               <option value=\"02\">031</option>\r\n");
      out.write("               <option value=\"02\">010</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            </div>         \r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("            <input type=\"text\" class=\"phone_back\" name=\"phone2\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("            <input type=\"text\" class=\"phone_back\" name=\"phone3\">\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"gender\">성별 : </label> \r\n");
      out.write("            </div>   \r\n");
      out.write("            <div class=\"col-75\">   \r\n");
      out.write("               <input type=\"radio\" value=\"M\" name=\"gender\" checked id=\"gender\"> 남자\r\n");
      out.write("               \r\n");
      out.write("               <input type=\"radio\"   value=\"F\" name=\"gender\"> 여자 \r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"birth\">생일 : </label>\r\n");
      out.write("            </div>   \r\n");
      out.write("            <div class=\"col-65\">\r\n");
      out.write("                <input type=\"date\" id=\"birth\" name=\"birth\">\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-25\">\r\n");
      out.write("               <label for=\"profile\">프로필 : </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-75\">\r\n");
      out.write("             <img id=\"output_image\" />\r\n");
      out.write("                <input type=\"file\" accept=\"image/*\"\r\n");
      out.write("               onchange=\"preview_image(event)\" name=\"image\">\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"store_bottom\">\r\n");
      out.write("         <input type=\"hidden\" name=\"grade\" value=\"N\">\r\n");
      out.write("         <input type=\"submit\" value=\"가입하기\">\r\n");
      out.write("         </div>\r\n");
      out.write("                 \r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
