/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-04 05:57:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class store_005fregist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script> function setImage(event) {\r\n");
      out.write("\tfor (var image of event.target.files) { \r\n");
      out.write("\t\tvar reader = new FileReader(); reader.onload = \r\n");
      out.write("\t\t\tfunction(event) {\r\n");
      out.write("\t\t\tvar img = document.createElement(\"img\"); img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("\t\t\tdocument.querySelector(\"div#image_container\").appendChild(img); }; \r\n");
      out.write("\t\t\tconsole.log(image); reader.readAsDataURL(image); } } \r\n");
      out.write("</script>\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/store_regist.css\">\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"store_container\">\r\n");
      out.write("\t\t<form action=\"/action_page.php\" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"sidebar\">\r\n");
      out.write("\t\t\t\t <a class=\"active\" href=\"#home\">업체 등록</a>\r\n");
      out.write("\t\t\t\t <a href=\"#\">업체 관리</a> \r\n");
      out.write("\t\t\t\t <a href=\"#\">업체 철회</a>\r\n");
      out.write("\t\t\t\t <a href=\"#\">기타 항목</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_name\">사업자 번호 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"store_name\" name=\"store_name\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"사업자 번호를 입력해주세요 . ex)1111-서울서초-111111\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_name\">가게 이름 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"store_name\" name=\"store_name\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"가게 이름(상호명)을 입력해 주세요.ex) 우리동네맛집\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_ceo\">대표자 이름 :</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"store_ceo\" name=\"store_ceo\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"대표자 이름을 입력하세요 ex)홍길동\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_tel\">전화 번호 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"store_tel\" name=\"store_tel\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"전화번호를 입력하세요 .ex)010-1234-5678\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_addr\">주소 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<select id=\"store_addr\" name=\"store_addr\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"select\">---- 선택하세요 ----</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"sinchon\">신촌</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"yongsan\">용산</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"jongro\">종로</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"ansan\">안산</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"anyang\">안양</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"jansil\">잠실</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"gangnam\">강남</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"hongdae\">홍대</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_addr\">업종분류 선택 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<select id=\"store_addr\" name=\"store_addr\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"select\">---- 선택하세요 ----</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"korean\">한식</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"china\">중식</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"japan\">일식</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"chicken\">치킨</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"pizaa\">피자</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"snackbar\">분식</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"midnight\">야식</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"desset\">디저트/카페</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"otc\">기타</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"subject\">업체 상세 설명 </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-75\">\r\n");
      out.write("\t\t\t\t\t<textarea id=\"subject\" name=\"subject\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"업체의 메뉴 , 가격 , 특징 등 상세 설명을 해주세요 \"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 200px\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-25\">\r\n");
      out.write("\t\t\t\t\t<label for=\"store_image\">가게 이미지 등록 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input multiple=\"multiple\" type=\"file\" id=\"image\" name=\"file\" accept=\"image/*\" \r\n");
      out.write("\t\t\t\tonchange=\"setImage(event)\"/>\r\n");
      out.write("\t\t\t\t<!-- <input type=\"button\" value=\"다시입력\" /> -->\r\n");
      out.write("\t\t\t\t<div class=\"col-75\" id=\"image_container\"></div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"store_bottom\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"등록하기 \">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
